config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get "/dashboard", to: "users#dashboard"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :arenas do
    resources :bookings, only: :create # [:new, :create, :index]
    #resources :users, only: :dashboard
  end

  resources :bookings, only: [:show] do
    member do
      patch :accept
      patch :decline
    end
  end

  # put "bookings/:id/accept", to: "bookings#accept", as: :accept
  # put "bookings/:id/decline", to: "bookings#decline", as: :decline

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arena.rb
class Arena < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :arena
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :arenas, dependent: :destroy
  has_many :bookings
  has_many :bookings_as_owner, through: :arenas, source: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :dashboard], unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/arenas_controller.rb
class ArenasController < ApplicationController
  before_action :set_arena, only: [:show, :edit, :update, :destroy]

  def index
    @arenass = Arena.all

  end

  def show
    @booking = Booking.new
    authorize @arena
    @arenas = Arena.geocoded #returns flats with coordinates

    @markers = @arenas.map do |arena|
      {
        lat: arena.latitude,
        lng: arena.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { arena: arena })
      }
    end
  end

  def new
    @arena = Arena.new
    authorize @arena
  end

  def create
    @arena = Arena.new(arena_params)
    @arena.user = current_user
    authorize @arena
    if @arena.save
      redirect_to arena_path(@arena)
    else
      render :new
    end
  end

  def edit
    authorize @arena
  end

  def update
    authorize @arena
    @arena.update(arena_params)
    redirect_to arenas_path
  end

  def destroy
    authorize @arena
    @arena.destroy
    redirect_to arenas_path
  end

  private

  def arena_params
    params.require(:arena).permit(:title, :description, :adress, :photo, :price)
  end

  def set_arena
    @arena = Arena.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @arena = Arena.find(params[:arena_id])
    @booking = Booking.new
  end

  def create
    @arena = Arena.find(params[:arena_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.arena = @arena
    @booking.price = @arena.price
    @booking.status = "pending"
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @arena = Arena.find(@booking.arena_id)
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "declined"
    @booking.save
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :arena_id, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @arenas = Arena.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @arenas = current_user.arenas
    @bookings = current_user.bookings
    @my_bookings = current_user.bookings_as_owner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arenas/_form.html.erb
<div class="container">
  <div class="row justify-content-center align-item-center">
    <div class="col-6">
      <div class="fight-form" data-aos="fade-down"
     data-aos-easing="linear"
     data-aos-duration="1500">


        <%= simple_form_for @arena do |f| %>

          <%= f.input :title, placeholder: "Title", label: false %>

          <%= f.input :address, label: false, placeholder: "Address" %>

          <%= f.input :description, label: false, placeholder: "Description" %>
          <%= f.input :price, label: false, placeholder: "Price per day" %>

          <%= f.input :photo, input_html: { id: 'photo-input'}, label: false %>

          <%= f.input :photo_cache, as: :hidden %>


            <div class="d-flex justify-content-between">
              <button type="button" class="btn btn-primary review-btn" data-toggle="modal" data-target="#exampleModalCenter">
                  Review Your Arena
              </button>

              <%= f.submit %>

            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->

app/views/arenas/_info_window.html.erb
<h2><%= arena.title %></h2>
<p><%= arena.address %></p>

app/views/arenas/edit.html.erb
<h1>Edit</h1>
<%= render "form" %>

<%= link_to arena_path(@arena), method: :delete, data: { confirm: "Are you sure?"} do %>
<i class="fas fa-trash"></i>
<% end %>

<%= link_to "Back to all arenas", arenas_path %>

app/views/arenas/index.html.erb
    <div class= "container">
      <div class="cards pt-5">
        <% @arenass.each do |arena| %>
        <div class="card zoom" data-aos="zoom-in-up">
          <div class="card-picture" data-id="<%= arena.id %>">
            <% if !arena.photo.nil? %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= image_path arena.photo, height: 300, width: 400, crop: :fill %>')">
              </div>
            <% else %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('https://images.unsplash.com/photo-1519741347686-c1e0aadf4611?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1980&q=80')">
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h2>🥊 <%= arena.title %></h2>
              <p class="card-text">🧮<%=  arena.price %>€</p>
              <p class="card-text">📌<%=  arena.address %></p>
              <p class="card-text">📝<%=  arena.description %></p>
          </div>
        </div>
        <% end %>
      </div>
    </div>

app/views/arenas/new.html.erb
<div class="container-test kenburns-top" style="background-image: linear-gradient(rgba(255,255,255,0.5), rgba(255,255,255,0.5)), url('https://cdn.vox-cdn.com/thumbor/fF1xaW1l5fGdLyuX3PRm7S87flU=/0x0:1100x733/1200x800/filters:focal(0x0:1100x733)/cdn.vox-cdn.com/uploads/chorus_image/image/45812056/102_MGM.0.jpg');background-size: cover; ">
    <%= render "form" %>

</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Your Arena</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
<div class="card zoom" data-aos="zoom-in-up">
  <div class="card-picture">
      <%= image_tag "", width: 400, class: "hidden", id: "photo-preview" %>
  </div>
  <div class="card-body">
    <h2><span class="title-modal"></span></h2>
      <p class="card-text"><span class="description-modal"></span></p>
      <p class="card-text"><span class="price-modal"></span>€</p>
  </div>
</div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>





<%= link_to "Back to all arenas", arenas_path %>



</div>

app/views/arenas/show.html.erb
<div class="m-5">
  <div class="row">
    <div class="col-11" style="margin:auto;">
      <div class="">

        <div class="d-flex justify-content-around align-item-center my-3">
          <div class="m-2">

            <%= link_to "Back to all arenas", arenas_path %>
            <h1><%= @arena.title %></h1> <h2><%=@arena.price%>€</h2>
            <h2> <%= @arena.address%></h2>
            <p><%=@arena.description%></p>

              <% if policy(@arena).update? %>
                <%= link_to edit_arena_path do %>
                  <i class="fas fa-pencil-alt"></i>
                <% end %>
              <% end %>

              <% if policy(@arena).destroy? %>
                <%= link_to arena_path, method: :delete, data: { confirm: "Are you sure?"} do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              <% end %>
          </div>
          <div class="m-2">
             <%= cl_image_tag(@arena.photo, style: "height: 350px")%>
          </div>

          <div class="m-2 bg-white p-3 h-100">
            <% if policy(Booking.new(arena_id: @arena.id)).create? %>
              <%= simple_form_for [@arena, @booking] do |f| %>
                <%= f.input :start_at, as: :string %>
                <%= f.input :ends_at, as: :string %>
                <%= f.submit "Book this arena", class: "btn btn-primary" %>
              <% end %>
            <% end %>

          </div>
        </div>

      </div>

      <div
        id="map"
        style="width: 100%;
        height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FightClubPaname</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"><!-- Uncomment if you import CSS in app/javascript/packs/application.js -->


  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <div class="footer fixed-bottom bg-white">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Made with 🥊 from la Team Bagarre
      </div>
    </div>

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);">
  <div class="container">
    <h1>The Fight Club Paname brings <strong>fighting skills</strong> to <strong> coding people </strong>!</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <!-- <a class="btn btn-flat btn-primary" href="#">Book an Arena</a> -->
    <h2><%= link_to "Choose your arena", arenas_path, :class=>"btn btn-primary"%></h2>
  </div>
</div>

<div class= "container">
    <h2 class="mt-3 text-center">The Lastest Arenas</h2>
  <div class="cards">
    <% @arenas.last(6).each do |arena| %>
        <div class="card zoom">
          <div class="card-picture" data-id="<%= arena.id %>">
            <% if !arena.photo.nil? %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path arena.photo, height: 300, width: 400, crop: :fill %>')">
              </div>
            <% else %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('https://images.unsplash.com/photo-1519741347686-c1e0aadf4611?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1980&q=80')">
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h4><%= arena.title %></h4>
          </div>
        </div>
        <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top bg-white" >
  <%= link_to arenas_path, class: "navbar-brand" do %>
    <i class="fas fa-fist-raised text-danger Width 100%"></i> Fight Club Paname
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Add an arena", new_arena_path, class: "nav-link #{"home-nav-item color-black" if params[:controller] == "arenas" && params[:action] == "index"}" %>
        </li>
        <li class="nav-item">
          <%= link_to "My dashboard", "/dashboard", class: "nav-link #{"home-nav-item color-black" if params[:controller] == "arenas" && params[:action] == "index"}" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars3.githubusercontent.com/u/40268689?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h1><%= "#{current_user.first_name}" %></h1>


      <h2>Vos arenas proposés à la location :</h2>
      <% if @arenas.size > 0 %>

<div class="cards">
        <% @arenas.each do |arena| %>
        <div class="card zoom" data-aos="zoom-in-up">
          <div class="card-picture" data-id="<%= arena.id %>">
            <% if !arena.photo.nil? %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= image_path arena.photo, height: 300, width: 400, crop: :fill %>')">
              </div>
            <% else %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('https://images.unsplash.com/photo-1519741347686-c1e0aadf4611?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1980&q=80')">
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h2>🥊 <%= arena.title %></h2>
              <p class="card-text">🧮<%=  arena.price %>€</p>
              <p class="card-text">📌<%=  arena.address %></p>
          </div>
        </div>
        <% end %>
      </div>
      <% else %>
        <span> Vous n'avez pas d'arènes en locations</span>
      <% end %>

      <div class="">
        <h2>Your bookings as a fighter</h2>

        <div class="cards">
          <% @bookings.each do |booking| %>
          <div class="card zoom" data-aos="zoom-in-up">
            <div class="card-picture" data-id="<%= booking.arena.id %>">
              <% if !booking.arena.photo.nil? %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
             url('<%= image_path booking.arena.photo, height: 300, width: 400, crop: :fill %>')">
                </div>
              <% else %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
             url('https://images.unsplash.com/photo-1519741347686-c1e0aadf4611?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1980&q=80')">
                </div>
              <% end %>
            </div>
            <div class="card-body">
              <h2>🥊 <%= booking.arena.title %></h2>
                <p class="card-text">🧮<%=  booking.arena.price %>€</p>
                <p class="card-text">📌<%=  booking.arena.address %></p>
                <% if booking.status == 'accepted' %>
                <p class="card-text">status : <span class="green"><%= booking.status %></span> </p>
                <% elsif booking.status == 'pending' %>
                <p class="card-text">status : <span class="orange"><%= booking.status %></span> </p>
                <% else %>
                <p class="card-text">status : <span class="red"><%= booking.status %></span></p>
                <% end %>

            </div>
          </div>
          <% end %>
        </div>
      </div>

      <div class="">
        <h2>Your bookings as a owner</h2>

        <div class="cards">
          <% @my_bookings.each do |booking| %>
          <% if booking.status == "pending" %>
          <div class="card zoom" data-aos="zoom-in-up">
            <div class="card-picture" data-id="<%= booking.arena.id %>">
              <% if !booking.arena.photo.nil? %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
             url('<%= image_path booking.arena.photo, height: 300, width: 400, crop: :fill %>')">
                </div>
              <% else %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
             url('https://images.unsplash.com/photo-1519741347686-c1e0aadf4611?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1980&q=80')">
                </div>
              <% end %>
            </div>
            <div class="card-body">
              <h2>🥊 <%= booking.arena.title %></h2>
                <p class="card-text">🧮<%=  booking.arena.price %>€</p>
                <p class="card-text">📌<%=  booking.arena.address %></p>
                <p class="card-text">status : <%= booking.status %> </p>
                <p><%= link_to "accept", accept_booking_path(booking), method: :patch, class: 'btn btn-success' %></p>
                <p><%= link_to "decline", decline_booking_path(booking), method: :patch, class: 'btn btn-danger' %></p>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>

​    </div>
​  </div>
​</div>